import week1Image from 'images/runners/runner1.svg';
import week2Image from 'images/runners/runner2.svg';
import week3Image from 'images/runners/runner3.svg';
import week4Image from 'images/runners/runner4.svg';
import week5Image from 'images/runners/runner5.svg';
import week6Image from 'images/runners/runner6.svg';
import week7Image from 'images/runners/runner7.svg';
import week8Image from 'images/runners/runner8.svg';
import runningImg from 'images/running.gif';
import walkingImg from 'images/walking.gif';
import { IWeek } from 'types/types';

export const defWeeks: IWeek[] = [
  {
    id: 1,
    is_passed: false,
    order: 1,
    title: 'Week 1',
    image: week1Image,
    trainings: [
      {
        id: 1,
        workout_duration: '30 minutes',
        clear_duration: 1200,
        is_passed: false,
        order: 1,
        title: 'Workout 1',
        image: '',
        duration: 1200,
        repetitions_number: 7,
        has_warm_up: true,
        has_cool_down: true,
        week: 1,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 60,
            training: 1,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 90,
            training: 1,
          },
        ],
      },
      {
        id: 2,
        workout_duration: '30 minutes',
        clear_duration: 1200,
        is_passed: false,
        order: 2,
        title: 'Workout 2',
        image: '',
        duration: 1200,
        repetitions_number: 7,
        has_warm_up: true,
        has_cool_down: true,
        week: 1,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 60,
            training: 2,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 90,
            training: 2,
          },
        ],
      },
      {
        id: 3,
        workout_duration: '30 minutes',
        clear_duration: 1200,
        is_passed: false,
        order: 3,
        title: 'Workout 3',
        image: '',
        duration: 1200,
        repetitions_number: 7,
        has_warm_up: true,
        has_cool_down: true,
        week: 1,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 60,
            training: 3,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 90,
            training: 3,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    is_passed: false,
    order: 2,
    title: 'Week 2',
    image: week2Image,
    trainings: [
      {
        id: 4,
        workout_duration: '30 minutes',
        clear_duration: 1260,
        is_passed: false,
        order: 1,
        title: 'Workout 1',
        image: '',
        duration: 1860,
        repetitions_number: 6,
        has_warm_up: true,
        has_cool_down: true,
        week: 2,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 90,
            training: 4,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 120,
            training: 4,
          },
        ],
      },
      {
        id: 5,
        workout_duration: '30 minutes',
        clear_duration: 1260,
        is_passed: false,
        order: 1,
        title: 'Workout 2',
        image: '',
        duration: 1860,
        repetitions_number: 6,
        has_warm_up: true,
        has_cool_down: true,
        week: 2,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 90,
            training: 5,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 120,
            training: 5,
          },
        ],
      },
      {
        id: 6,
        workout_duration: '30 minutes',
        clear_duration: 1260,
        is_passed: false,
        order: 1,
        title: 'Workout 3',
        image: '',
        duration: 1860,
        repetitions_number: 6,
        has_warm_up: true,
        has_cool_down: true,
        week: 2,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 90,
            training: 6,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 120,
            training: 6,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    is_passed: false,
    order: 3,
    title: 'Week 3',
    image: week3Image,
    trainings: [
      {
        id: 7,
        workout_duration: '28 minutes',
        clear_duration: 1080,
        is_passed: false,
        order: 1,
        title: 'Workout 1',
        image: '',
        duration: 1680,
        repetitions_number: 2,
        has_warm_up: true,
        has_cool_down: true,
        week: 3,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 90,
            training: 7,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 90,
            training: 7,
          },
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 3,
            duration: 180,
            training: 7,
          },
          {
            id: 4,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 4,
            duration: 180,
            training: 7,
          },
        ],
      },
      {
        id: 8,
        workout_duration: '28 minutes',
        clear_duration: 1080,
        is_passed: false,
        order: 1,
        title: 'Workout 2',
        image: '',
        duration: 1680,
        repetitions_number: 2,
        has_warm_up: true,
        has_cool_down: true,
        week: 3,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 90,
            training: 8,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 90,
            training: 8,
          },
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 3,
            duration: 180,
            training: 8,
          },
          {
            id: 4,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 4,
            duration: 180,
            training: 8,
          },
        ],
      },
      {
        id: 9,
        workout_duration: '28 minutes',
        clear_duration: 1080,
        is_passed: false,
        order: 1,
        title: 'Workout 3',
        image: '',
        duration: 1680,
        repetitions_number: 2,
        has_warm_up: true,
        has_cool_down: true,
        week: 3,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 90,
            training: 9,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 90,
            training: 9,
          },
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 3,
            duration: 180,
            training: 9,
          },
          {
            id: 4,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 4,
            duration: 180,
            training: 9,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    is_passed: false,
    order: 4,
    title: 'Week 4',
    image: week4Image,
    trainings: [
      {
        id: 10,
        workout_duration: '34 minutes',
        clear_duration: 1440,
        is_passed: false,
        order: 1,
        title: 'Workout 1',
        image: '',
        duration: 2040,
        repetitions_number: 2,
        has_warm_up: true,
        has_cool_down: true,
        week: 4,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 180,
            training: 10,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 90,
            training: 10,
          },
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 3,
            duration: 300,
            training: 10,
          },
          {
            id: 4,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 4,
            duration: 150,
            training: 10,
          },
        ],
      },
      {
        id: 11,
        workout_duration: '34 minutes',
        clear_duration: 1440,
        is_passed: false,
        order: 1,
        title: 'Workout 2',
        image: '',
        duration: 2040,
        repetitions_number: 2,
        has_warm_up: true,
        has_cool_down: true,
        week: 4,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 180,
            training: 11,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 90,
            training: 11,
          },
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 3,
            duration: 300,
            training: 11,
          },
          {
            id: 4,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 4,
            duration: 150,
            training: 11,
          },
        ],
      },
      {
        id: 12,
        workout_duration: '34 minutes',
        clear_duration: 1440,
        is_passed: false,
        order: 1,
        title: 'Workout 3',
        image: '',
        duration: 2040,
        repetitions_number: 2,
        has_warm_up: true,
        has_cool_down: true,
        week: 4,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 180,
            training: 12,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 90,
            training: 12,
          },
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 3,
            duration: 300,
            training: 12,
          },
          {
            id: 4,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 4,
            duration: 150,
            training: 12,
          },
        ],
      },
    ],
  },
  {
    id: 5,
    is_passed: false,
    order: 5,
    title: 'Week 5',
    image: week5Image,
    trainings: [
      {
        id: 13,
        workout_duration: '34 minutes',
        clear_duration: 1440,
        is_passed: false,
        order: 1,
        title: 'Workout 1',
        image: '',
        duration: 2040,
        repetitions_number: 3,
        has_warm_up: true,
        has_cool_down: true,
        week: 5,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 300,
            training: 13,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 180,
            training: 13,
          },
        ],
      },
      {
        id: 14,
        workout_duration: '36 minutes',
        clear_duration: 1560,
        is_passed: false,
        order: 1,
        title: 'Workout 2',
        image: '',
        duration: 2160,
        repetitions_number: 2,
        has_warm_up: true,
        has_cool_down: true,
        week: 5,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 480,
            training: 14,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 300,
            training: 14,
          },
        ],
      },
      {
        id: 15,
        workout_duration: '30 minutes',
        clear_duration: 1200,
        is_passed: false,
        order: 1,
        title: 'Workout 3',
        image: '',
        duration: 1800,
        repetitions_number: 1,
        has_warm_up: true,
        has_cool_down: true,
        week: 5,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 1200,
            training: 15,
          },
        ],
      },
    ],
  },
  {
    id: 6,
    is_passed: false,
    order: 6,
    title: 'Week 6',
    image: week6Image,
    trainings: [
      {
        id: 16,
        workout_duration: '28 minutes',
        clear_duration: 1440,
        is_passed: false,
        order: 1,
        title: 'Workout 1',
        image: '',
        duration: 2040,
        repetitions_number: 1,
        has_warm_up: true,
        has_cool_down: true,
        week: 6,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 300,
            training: 16,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 180,
            training: 16,
          },
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 3,
            duration: 480,
            training: 16,
          },
          {
            id: 4,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 4,
            duration: 180,
            training: 16,
          },
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 5,
            duration: 300,
            training: 16,
          },
        ],
      },
      {
        id: 17,
        workout_duration: '36 minutes',
        clear_duration: 1560,
        is_passed: false,
        order: 1,
        title: 'Workout 2',
        image: '',
        duration: 2160,
        repetitions_number: 2,
        has_warm_up: true,
        has_cool_down: true,
        week: 6,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 600,
            training: 17,
          },
          {
            id: 2,
            exercise_type: {
              title: 'Fast walking',
              image: walkingImg,
            },
            order: 2,
            duration: 180,
            training: 17,
          },
        ],
      },
      {
        id: 18,
        workout_duration: '35 minutes',
        clear_duration: 1500,
        is_passed: false,
        order: 1,
        title: 'Workout 3',
        image: '',
        duration: 2100,
        repetitions_number: 1,
        has_warm_up: true,
        has_cool_down: true,
        week: 6,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 1500,
            training: 18,
          },
        ],
      },
    ],
  },
  {
    id: 7,
    is_passed: false,
    order: 3,
    title: 'Week 7',
    image: week7Image,
    trainings: [
      {
        id: 19,
        workout_duration: '35 minutes',
        clear_duration: 1500,
        is_passed: false,
        order: 1,
        title: 'Workout 1',
        image: '',
        duration: 2100,
        repetitions_number: 1,
        has_warm_up: true,
        has_cool_down: true,
        week: 7,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 1500,
            training: 19,
          },
        ],
      },
      {
        id: 20,
        workout_duration: '35 minutes',
        clear_duration: 1500,
        is_passed: false,
        order: 1,
        title: 'Workout 2',
        image: '',
        duration: 2100,
        repetitions_number: 1,
        has_warm_up: true,
        has_cool_down: true,
        week: 7,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 1500,
            training: 20,
          },
        ],
      },
      {
        id: 21,
        workout_duration: '35 minutes',
        clear_duration: 1500,
        is_passed: false,
        order: 1,
        title: 'Workout 3',
        image: '',
        duration: 2100,
        repetitions_number: 1,
        has_warm_up: true,
        has_cool_down: true,
        week: 7,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 1500,
            training: 21,
          },
        ],
      },
    ],
  },
  {
    id: 8,
    is_passed: false,
    order: 8,
    title: 'Week 8',
    image: week8Image,
    trainings: [
      {
        id: 22,
        workout_duration: '38 minutes',
        clear_duration: 1680,
        is_passed: false,
        order: 1,
        title: 'Workout 1',
        image: '',
        duration: 2280,
        repetitions_number: 1,
        has_warm_up: true,
        has_cool_down: true,
        week: 8,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 1680,
            training: 8,
          },
        ],
      },
      {
        id: 23,
        workout_duration: '38 minutes',
        clear_duration: 1680,
        is_passed: false,
        order: 1,
        title: 'Workout 2',
        image: '',
        duration: 2280,
        repetitions_number: 1,
        has_warm_up: true,
        has_cool_down: true,
        week: 8,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 1680,
            training: 23,
          },
        ],
      },
      {
        id: 24,
        workout_duration: '38 minutes',
        clear_duration: 1680,
        is_passed: false,
        order: 1,
        title: 'Workout 3',
        image: '',
        duration: 2280,
        repetitions_number: 1,
        has_warm_up: true,
        has_cool_down: true,
        week: 8,
        exercises: [
          {
            id: 1,
            exercise_type: {
              title: 'Running',
              image: runningImg,
            },
            order: 1,
            duration: 1680,
            training: 24,
          },
        ],
      },
    ],
  },
];
